### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by andy-h-2016** [gustavochavarria/save-html-as-image#21]
Error message below while running `npm install save-html-as-image`

```zsh
npm ERR! prepareGitDep > canvas@1.1.6 install /Users/#########/.npm/_cacache/tmp/git-clone-12f01340/node_modules/canvas
npm ERR! prepareGitDep > node-gyp rebuild
npm ERR! prepareGitDep 
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/canvas-postbuild.node
npm ERR! prepareGitDep   CXX(target) Release/obj.target/canvas/src/Canvas.o
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > husky@4.3.8 install /Users/#########/.npm/_cacache/tmp/git-clone-12f01340/node_modules/husky
npm ERR! prepareGitDep > node husky install
npm ERR! prepareGitDep 
npm ERR! prepareGitDep husky > Setting up git hooks
npm ERR! prepareGitDep husky > Done
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > core-js@3.20.0 postinstall /Users/#########/.npm/_cacache/tmp/git-clone-12f01340/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep 
npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js:
npm ERR! prepareGitDep > https://opencollective.com/core-js 
npm ERR! prepareGitDep > https://patreon.com/zloirock 
npm ERR! prepareGitDep > https://paypal.me/zloirock 
npm ERR! prepareGitDep > bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > @fortawesome/fontawesome-free@5.15.4 postinstall /Users/#########/.npm/_cacache/tmp/git-clone-12f01340/node_modules/@fortawesome/fontawesome-free
npm ERR! prepareGitDep > node attribution.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Font Awesome Free 5.15.4 by @fontawesome - https://fontawesome.com
npm ERR! prepareGitDep License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > husky@4.3.8 postinstall /Users/#########/.npm/_cacache/tmp/git-clone-12f01340/node_modules/husky
npm ERR! prepareGitDep > opencollective-postinstall || exit 0
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Thank you for using husky!
npm ERR! prepareGitDep If you rely on this package, please consider supporting our open collective:
npm ERR! prepareGitDep > https://opencollective.com/husky/donate
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > html-to-image@1.7.0 prepare /Users/#########/.npm/_cacache/tmp/git-clone-12f01340
npm ERR! prepareGitDep > run-s build
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > html-to-image@1.7.0 prebuild /Users/#########/.npm/_cacache/tmp/git-clone-12f01340
npm ERR! prepareGitDep > run-s lint clean
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > html-to-image@1.7.0 lint /Users/#########/.npm/_cacache/tmp/git-clone-12f01340
npm ERR! prepareGitDep > tslint ./src/*.ts -c tslint.json -p tsconfig.json --fix
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > html-to-image@1.7.0 clean /Users/#########/.npm/_cacache/tmp/git-clone-12f01340
npm ERR! prepareGitDep > rimraf dist es lib
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > html-to-image@1.7.0 build /Users/#########/.npm/_cacache/tmp/git-clone-12f01340
npm ERR! prepareGitDep > run-s build:esm build:cjs build:umd
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > html-to-image@1.7.0 build:esm /Users/#########/.npm/_cacache/tmp/git-clone-12f01340
npm ERR! prepareGitDep > tsc --module esnext --target es2015 --outDir ./es
npm ERR! prepareGitDep 
npm ERR! prepareGitDep src/embedWebFonts.ts:213:7 - error TS2801: This condition will always return true since this 'Promise<void | { url: string; cssText: Promise<string>; }>' is always defined.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 213   if (cssFetchPromiseStore[url]) {
npm ERR! prepareGitDep           ~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! prepareGitDep 
npm ERR! prepareGitDep   src/embedWebFonts.ts:213:7
npm ERR! prepareGitDep     213   if (cssFetchPromiseStore[url]) {
npm ERR! prepareGitDep               ~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! prepareGitDep     Did you forget to use 'await'?
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep Found 1 error.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! prepareGitDep npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! prepareGitDep npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! prepareGitDep In file included from ../src/Canvas.cc:7:
npm ERR! prepareGitDep ../src/Canvas.h:19:10: fatal error: 'cairo/cairo.h' file not found
npm ERR! prepareGitDep #include <cairo/cairo.h>
npm ERR! prepareGitDep          ^~~~~~~~~~~~~~~
npm ERR! prepareGitDep 1 error generated.
npm ERR! prepareGitDep make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
npm ERR! prepareGitDep gyp ERR! build error 
npm ERR! prepareGitDep gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.onExit (/Users/#########/.nvm/versions/node/v10.15.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! prepareGitDep gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
npm ERR! prepareGitDep gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm ERR! prepareGitDep gyp ERR! System Darwin 20.6.0
npm ERR! prepareGitDep gyp ERR! command "/Users/#########/.nvm/versions/node/v10.15.2/bin/node" "/Users/#########/.nvm/versions/node/v10.15.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! prepareGitDep gyp ERR! cwd /Users/#########/.npm/_cacache/tmp/git-clone-12f01340/node_modules/canvas
npm ERR! prepareGitDep gyp ERR! node -v v10.15.2
npm ERR! prepareGitDep gyp ERR! node-gyp -v v3.8.0
npm ERR! prepareGitDep gyp ERR! not ok 
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! html-to-image@1.7.0 build:esm: `tsc --module esnext --target es2015 --outDir ./es`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the html-to-image@1.7.0 build:esm script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/#########/.npm/_logs/2021-12-23T05_41_47_927Z-debug.log
npm ERR! prepareGitDep ERROR: "build:esm" exited with 1.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! html-to-image@1.7.0 build: `run-s build:esm build:cjs build:umd`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the html-to-image@1.7.0 build script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/#########/.npm/_logs/2021-12-23T05_41_47_962Z-debug.log
npm ERR! prepareGitDep ERROR: "build" exited with 1.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! html-to-image@1.7.0 prepare: `run-s build`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the html-to-image@1.7.0 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/#########/.npm/_logs/2021-12-23T05_41_48_018Z-debug.log
npm ERR! prepareGitDep 
```

**Comment by gustavochavarria** [comment]
Fixed in 1.7.1
